[package]
name = "sequencer"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
hex.workspace = true
dotenv.workspace = true