[package]
name = "prover"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy.workspace = true
futures-util.workspace = true
tokio.workspace = true
dotenv.workspace = true
hex.workspace = true
alloy-rlp.workspace = true