[package]
name = "node"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy.workspace = true
rand.workspace = true
serde.workspace = true
serde_json.workspace = true
futures-util.workspace = true
tokio.workspace = true
hex.workspace = true
alloy-rlp.workspace = true